version: "3.7"
services:
  ircbot:
    build:
      context: .
      dockerfile: mqtt-irc-bridge/Dockerfile
    container_name: ircbot
    environment:
      - IRC_MQTT_BROKER
      - IRC_MQTT_PORT
      - IRC_MQTT_USER
      - IRC_MQTT_PASS
      - IRC_NICKNAME
      - IRC_NICKSERV_PASS
      - IRC_SERVER
      - IRC_PORT
      - IRC_SSL
      - IRC_CHANNELS
      - IRC_WATCHLIST
    logging:
      driver: journald
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${IRC_DATA_PATH}:/data
