version: "3.7"
volumes:
  influxdb_data:
  influxdb_config:
  grafana_data:
  letsencrypt_config:
  letsencrypt_data:
  nginx_config:
  oauth2proxy_config:
services:
  # oauth2-proxy:
  #   image: quay.io/oauth2-proxy/oauth2-proxy
  #   container_name: oauth2-proxy
  #   volumes:
  #     - ./oauth2-proxy/proxy.cfg:/proxy.cfg:Z
  #   restart: always
  #   logging:
  #     driver: journald
  # nginx:
  #   image: docker.io/library/nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
  #     - letsencrypt_data:/etc/letsencrypt
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - oauth2-proxy
  #   restart: always
  #   logging:
  #     driver: journald
  influxdb:
    image: docker.io/influxdb/influxdb:latest
    container_name: influxdb
    environment:
      - ${DOCKER_INFLUXDB_INIT_PASSWORD:err}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_ORG=Home
      - DOCKER_INFLUXDB_INIT_BUCKET=Environment
    volumes:
      - influxdb_config:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2
    restart: always
    logging:
      driver: journald
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    environment:
      - ${GF_SECURITY_ADMIN_PASSWORD:err}
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    logging:
      driver: journald
  bridge:
    build:
      context: syslog-bridge
    container_name: bridge
    volumes:
      - /var/log/iot:/var/log/iot
      - influxdb_config:/etc/influxdb2
    restart: always
    logging:
      driver: journald
  weatherpoller:
    build:
      context: weather-poller
    container_name: weather-poller
    volumes:
      - influxdb_config:/etc/influxdb2
    restart: always
    logging:
      driver: journald
networks:
  default:
    name: iotcloud
