version: "3.7"
services:

  certbot:
    build:
      context: certbot
    image: ${CONTAINER_REGISTRY}/iotcloud_certbot

  chrony:
    build:
      context: chrony
    image: ${CONTAINER_REGISTRY}/iotcloud_chrony

  invencli:
    build:
      context: invencli
    image: ${CONTAINER_REGISTRY}/iotcloud_invencli

  mqtt-influx-bridge:
    build:
      context: mqtt-influx-bridge
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-influx-bridge

  mqtt-irc-bridge:
    build:
      context: mqtt-irc-bridge
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-irc-bridge

  mqtt-postgres-bridge:
    build:
      context: mqtt-postgres-bridge
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-postgres-bridge

  mqtt-telegram-bridge:
    build:
      context: mqtt-telegram-bridge
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-telegram-bridge

  proxy:
    build:
      context: proxy
    image: ${CONTAINER_REGISTRY}/iotcloud_proxy

  weather-poller:
    build:
      context: weather-poller
    image: ${CONTAINER_REGISTRY}/iotcloud_weather-poller
