version: "3.7"
volumes:
  data:
    driver_opts:
      type: cifs
      device: "${AZURE_SHARE}"
      o: "vers=3.1.1,rw,seal,uid=1000,${AZURE_CREDS}"
services:
  ircbot:
    image: ghcr.io/peterezzo/iotcloud_ircbot:latest
    container_name: ircbot
    environment:
      - IRC_MQTT_BROKER
      - IRC_MQTT_PORT
      - IRC_MQTT_USER
      - IRC_MQTT_PASS
      - IRC_NICKNAME
      - IRC_NICKSERV_PASS
      - IRC_SERVER
      - IRC_PORT
      - IRC_SSL
      - IRC_CHANNELS
      - IRC_WATCHLIST
    logging:
      driver: journald
    network_mode: host
    restart: unless-stopped
    volumes:
      - data:/data
