version: "3.7"

x-logging:
  &default-logging
  driver: journald

volumes:

  influxdb_data:
  influxdb_config:
  grafana_data:
  letsencrypt_data:
  mosquito_data:

networks:
  default:
    name: iotcloud
    driver: overlay
    attachable: true

services:

  certbot:
    image: ${CONTAINER_REGISTRY}/iotcloud_certbot:latest
    container_name: certbot
    environment:
      - DOMAIN
    logging: *default-logging
    volumes:
      - letsencrypt_data:/etc/letsencrypt

  coredns:
    image: docker.io/coredns/coredns
    container_name: coredns
    logging: *default-logging
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./coredns/Corefile:/config/Corefile
      - ./coredns/static.hosts:/config/static.hosts

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    logging: *default-logging
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

  influxdb:
    image: docker.io/library/influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_ORG=Home
      - DOCKER_INFLUXDB_INIT_BUCKET=Environment
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2

  mosquitto:
    image: docker.io/library/eclipse-mosquitto:2.0
    container_name: mosquitto
    depends_on:
      - certbot
    ports:
      - "1883:1883"
      - "8883:8883"
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/remote.password_file:/mosquitto/config/remote.password_file
      - mosquito_data:/mosquitto/data
      - letsencrypt_data:/etc/letsencrypt:ro

  mqtt-influx-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-influx-bridge:latest
    container_name: mqtt-influx-bridge
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - MQTT_BROKER
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2:ro

  mqtt-postgres-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-postgres-bridge:latest
    container_name: mqtt-postgres-bridge
    depends_on:
      - mosquitto
      - postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - MQTT_BROKER
      - PREAMBLE
    logging: *default-logging
    restart: unless-stopped

  mqtt-telegram-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-telegram-bridge:latest
    container_name: mqtt-telegram-bridge
    depends_on:
      - mosquitto
    environment:
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
      - MQTT_BROKER
    logging: *default-logging
    restart: unless-stopped

  postgres:
    image: docker.io/library/postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    logging: *default-logging
    restart: unless-stopped

  weather-poller:
    image: ${CONTAINER_REGISTRY}/iotcloud_weather-poller:latest
    container_name: weather-poller
    depends_on:
      - influxdb
    environment:
    - OBSERVATION_STATIONS
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2:ro
