version: "3.7"

x-logging:
  &default-logging
  driver: journald

volumes:

  influxdb_data:
  influxdb_config:
  grafana_data:
  letsencrypt_data:
  mosquito_data:

networks:
  default:
    name: iotcloud

services:

  autoheal:
    image: docker.io/willfarrell/autoheal
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  certbot:
    image: ${CONTAINER_REGISTRY}/iotcloud_certbot
    container_name: certbot
    environment:
      - DOMAIN
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - letsencrypt_data:/etc/letsencrypt

  chrony:
    image: ${CONTAINER_REGISTRY}/iotcloud_chrony
    container_name: chrony
    logging: *default-logging
    ports:
      - "123:123/udp"
    restart: unless-stopped

  coredns:
    image: docker.io/coredns/coredns
    container_name: coredns
    logging: *default-logging
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    volumes:
      - ./coredns/Corefile:/config/Corefile
      - ./coredns/static.hosts:/config/static.hosts

  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    logging: *default-logging
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

  influxdb:
    image: docker.io/library/influxdb
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_ORG=Home
      - DOCKER_INFLUXDB_INIT_BUCKET=Environment
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2

  mosquitto:
    image: docker.io/library/eclipse-mosquitto:2.0
    container_name: mosquitto
    depends_on:
      - certbot
    ports:
      - "1883:1883"
      - "8883:8883"
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/remote.password_file:/mosquitto/config/remote.password_file
      - mosquito_data:/mosquitto/data
      - letsencrypt_data:/etc/letsencrypt:ro

  mqtt-influx-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-influx-bridge
    container_name: mqtt-influx-bridge
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - MQTT_BROKER
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2:ro

  mqtt-irc-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-irc-bridge
    container_name: mqtt-irc-bridge
    depends_on:
      - proxy
    environment:
      - MQTT_BROKER
      - IRC_NICKNAME
      - IRC_NICKSERV_PASS
      - IRC_SERVER
      - IRC_PORT
      - IRC_SSL
      - IRC_CHANNELS
      - IRC_WATCHLIST
      - IRC_PROXY_HOST
      - IRC_PROXY_PORT
    logging:
      driver: journald
    restart: unless-stopped
    volumes:
      - ${DATA_VOLUME}:/data

  mqtt-postgres-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-postgres-bridge
    container_name: mqtt-postgres-bridge
    depends_on:
      - mosquitto
      - postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - MQTT_BROKER
      - PREAMBLE
    logging: *default-logging
    restart: unless-stopped

  mqtt-telegram-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_mqtt-telegram-bridge
    container_name: mqtt-telegram-bridge
    depends_on:
      - mosquitto
    environment:
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
      - MQTT_BROKER
    logging: *default-logging
    restart: unless-stopped

  nwsapi-influx-bridge:
    image: ${CONTAINER_REGISTRY}/iotcloud_nwsapi-influx-bridge
    container_name: nwsapi-influx-bridge
    depends_on:
      - influxdb
    environment:
    - OBSERVATION_STATIONS
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - influxdb_config:/etc/influxdb2:ro

  postgres:
    image: docker.io/library/postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    logging: *default-logging
    restart: unless-stopped

  proxy:
    image: ${CONTAINER_REGISTRY}/iotcloud_proxy
    container_name: proxy
    command: ${PROXY_HOST}
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ${PROXY_KEY}:/home/ssh/key:ro
