#!/bin/sh

CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

# confirm correct permissions on chrony run directory
if [ -d /run/chrony ]; then
  chown -R chrony:chrony /run/chrony
  chmod o-rx /run/chrony
  # remove previous pid file if it exist
  rm -f /var/run/chrony/chronyd.pid
fi

# confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
  chown -R chrony:chrony /var/lib/chrony
fi

## dynamically populate chrony config file.
{
  echo "# chrony.conf file generated by startup script"
  echo "# located at /docker-entrypoint.sh"
} > ${CHRONY_CONF_FILE}


# if NTP_SERVERS environment variable is not present, populate with default server
if [ -z "${NTP_SERVERS}" ]; then
  echo "pool pool.ntp.org iburst" >> ${CHRONY_CONF_FILE}
else
    IFS=","
    for N in $NTP_SERVERS; do
    # strip any quotes found before or after ntp server
    N_CLEANED=${N//\"}
    echo "server "${N_CLEANED}" iburst" >> ${CHRONY_CONF_FILE}
    done
fi

# final bits for the config file
{
  echo
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"
  echo "local stratum 10"
  echo "allow"
} >> ${CHRONY_CONF_FILE}

## startup chronyd in the foreground
exec /usr/sbin/chronyd $*
